/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_Sample1 */

#ifndef _Included_com_study_jnilearn_Sample1
#define _Included_com_study_jnilearn_Sample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_study_jnilearn_Sample1_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_study_jnilearn_Sample1_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    floatMethod
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_study_jnilearn_Sample1_floatMethod
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_jnilearn_Sample1_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_study_jnilearn_Sample1_intArrayMethod
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    stringArrayMethod
 * Signature: ([Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_jnilearn_Sample1_stringArrayMethod
  (JNIEnv *, jobject, jobjectArray, jstring);

/*
 * Class:     com_study_jnilearn_Sample1
 * Method:    init2array
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_study_jnilearn_Sample1_init2array
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
