/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_Sample5 */

#ifndef _Included_com_study_jnilearn_Sample5
#define _Included_com_study_jnilearn_Sample5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_Sample5
 * Method:    doit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample5_doit
  (JNIEnv *, jobject);

/*
 * Class:     com_study_jnilearn_Sample5
 * Method:    errorCodeCheck
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample5_errorCodeCheck
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
