/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_ThreadSync */

#ifndef _Included_com_study_jnilearn_ThreadSync
#define _Included_com_study_jnilearn_ThreadSync
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_ThreadSync
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_ThreadSync_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
