/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_Sample6 */

#ifndef _Included_com_study_jnilearn_Sample6
#define _Included_com_study_jnilearn_Sample6
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_Sample6
 * Method:    getEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample6_getEnv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
