/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_Sample3 */

#ifndef _Included_com_study_jnilearn_Sample3
#define _Included_com_study_jnilearn_Sample3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_Sample3
 * Method:    accessInstanceField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample3_accessInstanceField
  (JNIEnv *, jobject);

/*
 * Class:     com_study_jnilearn_Sample3
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample3_nativeMethod
  (JNIEnv *, jobject);

/*
 * Class:     com_study_jnilearn_Sample3
 * Method:    initIds
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample3_initIds
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
