/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_Sample2 */

#ifndef _Included_com_study_jnilearn_Sample2
#define _Included_com_study_jnilearn_Sample2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_Sample2
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample2_accessStaticField
  (JNIEnv *, jobject);

/*
 * Class:     com_study_jnilearn_Sample2
 * Method:    accessStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample2_accessStaticMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_study_jnilearn_Sample2
 * Method:    accessPrimaryInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample2_accessPrimaryInstanceMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
