/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_jnilearn_Sample4 */

#ifndef _Included_com_study_jnilearn_Sample4
#define _Included_com_study_jnilearn_Sample4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_jnilearn_Sample4
 * Method:    newString
 * Signature: ([CI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_jnilearn_Sample4_newString
  (JNIEnv *, jobject, jcharArray, jint);

/*
 * Class:     com_study_jnilearn_Sample4
 * Method:    testRefresh
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_study_jnilearn_Sample4_testRefresh
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
