/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testopensl_AudioRecordActivity */

#ifndef _Included_com_example_testopensl_AudioRecordActivity
#define _Included_com_example_testopensl_AudioRecordActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testopensl_AudioRecordActivity
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioRecordActivity_createEngine
(JNIEnv *, jobject);

/*
 * Class:     com_example_testopensl_AudioRecordActivity
 * Method:    createAudioRecord
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioRecordActivity_createAudioRecord
(JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_testopensl_AudioRecordActivity
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioRecordActivity_stop
(JNIEnv *, jobject);

/*
 * Class:     com_example_testopensl_AudioRecordActivity
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testopensl_AudioRecordActivity_shutdown
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
